server:
  port: 8000 

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/suppleit?serverTimezone=Asia/Seoul
    username: root
    password: abcd1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mybatis:
    configuration:
      default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.suppleit.backend.model

jwt:
  secret: ZmluYWxwcm9qZWN0c3VwcGxpdGZpbmFscHJvamVjdHN1cHBsaXQ= # finalprojectsupplitfinalprojectsupplit (base64 인코딩한거)
  expiration: 86400000  # 1일 (밀리초 단위)

naver:
  api:
    client-id: sARvjvVaomfrRVoYKUAw
    client-secret: omnlYbh5YN
    url : https://openapi.naver.com/v1/search/shop.json

flask:
  api:
    url: http://localhost:5000/recommend?keyword= # Flask 서버의 URL